import type { GitLabScanHistory, GitLabProjectResult } from "@/types";

export function generateWeeklyReport(history: GitLabScanHistory): string {
  const projects: GitLabProjectResult[] = JSON.parse(history.summary || "[]");
  const contributors: string[] = JSON.parse(history.contributors || "[]");
  const scanDate = new Date(history.scan_at).toLocaleDateString("zh-CN");

  const testCoverage = history.total_projects > 0
    ? Math.round((history.test_projects / history.total_projects) * 100)
    : 0;

  const noTestProjects = projects.filter((p) => !p.has_test);
  const pendingMrProjects = projects.filter((p) => p.pending_mrs > 0);

  // Sort projects by commits
  const sortedProjects = [...projects].sort((a, b) => b.commits - a.commits);

  // Calculate contribution
  const contributionMap = new Map<string, number>();
  projects.forEach((project) => {
    const perContributor = project.contributors.length > 0
      ? Math.floor(project.commits / project.contributors.length)
      : project.commits;
    project.contributors.forEach((contributor) => {
      contributionMap.set(contributor, (contributionMap.get(contributor) || 0) + perContributor);
    });
  });

  const topContributors = Array.from(contributionMap.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  let report = `# 本周代码提交报告

> 扫描时间：${scanDate}
> 扫描类型：${history.scan_type === "weekly" ? "定时扫描" : "手动扫描"}

## 📊 概览

| 指标 | 数值 |
|------|------|
| 扫描项目 | ${history.total_projects} 个 |
| 代码提交 | ${history.total_commits} 次 |
| 参与人员 | ${contributors.length} 人 |
| 单测覆盖 | ${testCoverage}% (${history.test_projects}/${history.total_projects}) |
| 待审MR | ${history.pending_mrs} 个 |

## 📈 代码变更

- **新增**: +${history.total_lines_added.toLocaleString()} 行
- **删除**: -${history.total_lines_removed.toLocaleString()} 行

## 📋 项目详情

| 项目 | 提交数 | 单测状态 | 待审MR |
|------|-------|---------|-------|
`;

  sortedProjects.forEach((project) => {
    const shortName = project.project_name.split("/").pop() || project.project_name;
    const testStatus = project.has_test ? "✅" : "❌";
    report += `| ${shortName} | ${project.commits} | ${testStatus} | ${project.pending_mrs} |
`;
  });

  if (noTestProjects.length > 0 || pendingMrProjects.length > 0) {
    report += `
## ⚠️ 需关注项目

`;
    noTestProjects.slice(0, 3).forEach((project) => {
      const shortName = project.project_name.split("/").pop() || project.project_name;
      report += `- **${shortName}**: ${project.commits}次提交，未发现单测
`;
    });

    pendingMrProjects.slice(0, 2).forEach((project) => {
      const shortName = project.project_name.split("/").pop() || project.project_name;
      report += `- **${shortName}**: ${project.pending_mrs}个MR待审核
`;
    });
  }

  if (topContributors.length > 0) {
    report += `
## 🏆 本周贡献TOP${topContributors.length}

| 排名 | 贡献者 | 提交数 |
|------|-------|-------|
`;
    topContributors.forEach(([name, commits], index) => {
      const medal = index === 0 ? "🥇" : index === 1 ? "🥈" : index === 2 ? "🥉" : `${index + 1}`;
      report += `| ${medal} | ${name} | ${commits} |
`;
    });
  }

  report += `
---
*Generated by Dev Tools*
`;

  return report;
}

export function downloadReport(report: string, filename: string): void {
  const blob = new Blob([report], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
